Refactor to proper abstract class
containers/udica pull request #77
Opened 2020-10-17 21:25 UTC by MartinBasti

EngineHelper is an abstract class and should be treated like abstract class using python stdlib tools

Signed-off-by: Martin Bašti <mbasti@redhat.com>

2020-10-19 07:52 UTC, JAORMX approved these changes

2020-10-19 07:55 UTC, JAORMX requested changes
While the change looks appropriate, seems that it's failing the format checks.
You can run `make format` locally to see what's up, or just do `make format` to get the tool to format this for you.

2020-10-19 08:10 UTC, MartinBasti commented
> While the change looks appropriate, seems that it's failing the format checks.
> You can run `make format` locally to see what's up, or just do `make format` to get the tool to format this for you.

It's fixed in PR #76 ; once that PR is merged I'll rebase. Also because this PR uses `ABC`, I'd limit support to py3.4+ afterwards

2020-10-19 15:28 UTC, MartinBasti commented
Rebased

2020-10-20 05:42 UTC, JAORMX approved these changes

2020-10-20 05:42 UTC, merged